
#define INVENTORY_NONE				0
//armor
#define INVENTORY_ARMOR				1
//weapons
#define INVENTORY_WEAPON0			4
#define INVENTORY_WEAPON1			5
#define INVENTORY_WEAPON2			6
#define INVENTORY_WEAPON3			7
#define INVENTORY_WEAPON4			8
#define INVENTORY_WEAPON5			9
#define INVENTORY_WEAPON6			10
#define INVENTORY_WEAPON7			11
#define INVENTORY_WEAPON8			13
/*#define INVENTORY_GRAPPLINGHOOK		14
#define INVENTORY_NAILGUN			15
#define INVENTORY_PROXLAUNCHER		16
#define INVENTORY_CHAINGUN			17*/
//ammo
#define INVENTORY_AMMO0				18
#define INVENTORY_AMMO1				19
#define INVENTORY_AMMO2				20
#define INVENTORY_AMMO3				21
#define INVENTORY_AMMO4				22
#define INVENTORY_AMMO5				23
#define INVENTORY_AMMO6				24
#define INVENTORY_AMMO7				25
#define INVENTORY_AMMO8				26
/*#define INVENTORY_MINES			27
#define INVENTORY_BELT				28*/
//powerups
#define INVENTORY_HEALTH			29
#define INVENTORY_SUBTANK			31

#define INVENTORY_REDFLAG			32
#define INVENTORY_BLUEFLAG			33

//enemy stuff
#define ENEMY_HORIZONTAL_DIST		200
#define ENEMY_HEIGHT				201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES		203


//item numbers (make sure they are in sync with bg_itemlist in bg_misc.c)
#define MODELINDEX_ARMORSHARD		1
#define MODELINDEX_ARMORCOMBAT		2
#define MODELINDEX_ARMORBODY		3
#define MODELINDEX_HEALTHSMALL		4
#define MODELINDEX_HEALTH			5
#define MODELINDEX_HEALTHLARGE		6
#define MODELINDEX_HEALTHMEGA		7

#define MODELINDEX_GAUNTLET			8
#define MODELINDEX_SHOTGUN			9
#define MODELINDEX_MACHINEGUN		10
#define MODELINDEX_GRENADELAUNCHER	11
#define MODELINDEX_ROCKETLAUNCHER	12
#define MODELINDEX_LIGHTNING		13
#define MODELINDEX_RAILGUN			14
#define MODELINDEX_PLASMAGUN		15
#define MODELINDEX_BFG10K			16
#define MODELINDEX_GRAPPLINGHOOK	17

#define MODELINDEX_SHELLS			18
#define MODELINDEX_BULLETS			19
#define MODELINDEX_GRENADES			20
#define MODELINDEX_CELLS			21
#define MODELINDEX_LIGHTNINGAMMO	22
#define MODELINDEX_ROCKETS			23
#define MODELINDEX_SLUGS			24
#define MODELINDEX_BFGAMMO			25

#define MODELINDEX_SUBTANK			26

#define MODELINDEX_REDFLAG			27
#define MODELINDEX_BLUEFLAG			28



//
#define WEAPONINDEX_WEAPON0				1
#define WEAPONINDEX_WEAPON1				2
#define WEAPONINDEX_WEAPON2				3
#define WEAPONINDEX_WEAPON3				4
#define WEAPONINDEX_WEAPON4				5
#define WEAPONINDEX_WEAPON5				6
#define WEAPONINDEX_WEAPON6				7
#define WEAPONINDEX_WEAPON7				8
#define WEAPONINDEX_WEAPON8				9
#define WEAPONINDEX_GRAPPLING_HOOK		10
#define WEAPONINDEX_NAILGUN				11
#define WEAPONINDEX_PROXLAUNCHER		12
#define WEAPONINDEX_CHAINGUN			13
